export { LoginPage } from './login/login';
export { LogoutPage } from './logout/logout';
export { RegisterPage } from './register/register';
export { ForgotPasswordPage } from './forgot-password/forgot-password';
export { ResetPasswordPage } from './reset-password/reset-password';
export { ProfilePage } from './profile/profile';
export { ConstructorPage } from './constructor/constructor';
export { IngredientPage } from './ingredient/ingredient';
export { NotFound404 } from './not-found/not-found';
